#############################################################################
# Makefile for building: PHPEditor
# Generated by qmake (3.0) (Qt 5.1.1) on: lun. sept. 30 21:57:39 2013
# Project:  PHPEditor.pro
# Template: subdirs
# Command: /opt/Qt/5.1.1/gcc/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile PHPEditor.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /opt/Qt/5.1.1/gcc/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-Core \
		sub-Application \
		sub-Plugins


sub-Core-qmake_all:  FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd Core/ && $(MAKE) -f Makefile qmake_all
sub-Core: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-Core-make_first-ordered: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Core-make_first: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Core-all-ordered: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Core-all: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Core-clean-ordered: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Core-clean: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Core-distclean-ordered: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Core-distclean: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Core-install_subtargets-ordered: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Core-install_subtargets: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Core-uninstall_subtargets-ordered: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Core-uninstall_subtargets: FORCE
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Application-qmake_all: sub-Core-qmake_all FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd Application/ && $(MAKE) -f Makefile qmake_all
sub-Application: FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-Application-make_first-ordered: sub-Core-make_first-ordered  FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Application-make_first: FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Application-all-ordered: sub-Core-all-ordered  FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Application-all: FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Application-clean-ordered: sub-Core-clean-ordered  FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Application-clean: FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Application-distclean-ordered: sub-Core-distclean-ordered  FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Application-distclean: FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Application-install_subtargets-ordered: sub-Core-install_subtargets-ordered  FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Application-install_subtargets: FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Application-uninstall_subtargets-ordered: sub-Core-uninstall_subtargets-ordered  FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Application-uninstall_subtargets: FORCE
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Plugins-qmake_all: sub-Application-qmake_all FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile
	cd Plugins/ && $(MAKE) -f Makefile qmake_all
sub-Plugins: FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile
sub-Plugins-make_first-ordered: sub-Application-make_first-ordered  FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Plugins-make_first: FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Plugins-all-ordered: sub-Application-all-ordered  FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Plugins-all: FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Plugins-clean-ordered: sub-Application-clean-ordered  FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Plugins-clean: FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Plugins-distclean-ordered: sub-Application-distclean-ordered  FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Plugins-distclean: FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Plugins-install_subtargets-ordered: sub-Application-install_subtargets-ordered  FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Plugins-install_subtargets: FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Plugins-uninstall_subtargets-ordered: sub-Application-uninstall_subtargets-ordered  FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Plugins-uninstall_subtargets: FORCE
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: PHPEditor.pro /opt/Qt/5.1.1/gcc/mkspecs/linux-g++/qmake.conf /opt/Qt/5.1.1/gcc/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/common/shell-unix.conf \
		/opt/Qt/5.1.1/gcc/mkspecs/common/unix.conf \
		/opt/Qt/5.1.1/gcc/mkspecs/common/linux.conf \
		/opt/Qt/5.1.1/gcc/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.1.1/gcc/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.1.1/gcc/mkspecs/common/g++-base.conf \
		/opt/Qt/5.1.1/gcc/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.1.1/gcc/mkspecs/qconfig.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_clucene.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_designercomponents.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_platformsupport.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_quickparticles.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_v8.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.1.1/gcc/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/qt_config.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/spec_post.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/default_pre.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/unix/default_pre.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/default_post.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/qml_debug.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/declarative_debug.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/warn_on.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/wayland-scanner.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/exceptions.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/yacc.prf \
		/opt/Qt/5.1.1/gcc/mkspecs/features/lex.prf \
		PHPEditor.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile PHPEditor.pro
/opt/Qt/5.1.1/gcc/mkspecs/features/spec_pre.prf:
/opt/Qt/5.1.1/gcc/mkspecs/common/shell-unix.conf:
/opt/Qt/5.1.1/gcc/mkspecs/common/unix.conf:
/opt/Qt/5.1.1/gcc/mkspecs/common/linux.conf:
/opt/Qt/5.1.1/gcc/mkspecs/common/gcc-base.conf:
/opt/Qt/5.1.1/gcc/mkspecs/common/gcc-base-unix.conf:
/opt/Qt/5.1.1/gcc/mkspecs/common/g++-base.conf:
/opt/Qt/5.1.1/gcc/mkspecs/common/g++-unix.conf:
/opt/Qt/5.1.1/gcc/mkspecs/qconfig.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_clucene.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_designercomponents.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_platformsupport.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_qmldevtools.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_quickparticles.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_script.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_v8.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/5.1.1/gcc/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/5.1.1/gcc/mkspecs/features/qt_functions.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/qt_config.prf:
/opt/Qt/5.1.1/gcc/mkspecs/linux-g++/qmake.conf:
/opt/Qt/5.1.1/gcc/mkspecs/features/spec_post.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/exclusive_builds.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/default_pre.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/unix/default_pre.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/resolve_config.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/default_post.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/qml_debug.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/declarative_debug.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/warn_on.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/wayland-scanner.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/testcase_targets.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/exceptions.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/yacc.prf:
/opt/Qt/5.1.1/gcc/mkspecs/features/lex.prf:
PHPEditor.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile PHPEditor.pro

qmake_all: sub-Core-qmake_all sub-Application-qmake_all sub-Plugins-qmake_all FORCE

make_first: sub-Core-make_first-ordered sub-Application-make_first-ordered sub-Plugins-make_first-ordered FORCE
all: sub-Core-all-ordered sub-Application-all-ordered sub-Plugins-all-ordered FORCE
clean: sub-Core-clean-ordered sub-Application-clean-ordered sub-Plugins-clean-ordered FORCE
distclean: sub-Core-distclean-ordered sub-Application-distclean-ordered sub-Plugins-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-Core-install_subtargets-ordered sub-Application-install_subtargets-ordered sub-Plugins-install_subtargets-ordered FORCE
uninstall_subtargets: sub-Core-uninstall_subtargets-ordered sub-Application-uninstall_subtargets-ordered sub-Plugins-uninstall_subtargets-ordered FORCE

sub-Core-check_ordered:
	@test -d Core/ || mkdir -p Core/
	cd Core/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Core/Core.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-Application-check_ordered: sub-Core-check_ordered 
	@test -d Application/ || mkdir -p Application/
	cd Application/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Application/Application.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
sub-Plugins-check_ordered: sub-Application-check_ordered 
	@test -d Plugins/ || mkdir -p Plugins/
	cd Plugins/ && ( test -e Makefile || $(QMAKE) /home/fabien/Projets/Qt/PHPEditor/Plugins/Plugins.pro -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-Core-check_ordered sub-Application-check_ordered sub-Plugins-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

